- name: setup postgresql server
  hosts: dbservers
  gather_facts: yes
  become: yes
  roles:
    - { role: install, tags: ["install"]}
    - { role: harden,  tags: ["harden"]}
    - { role: ssl,  tags: ["ssl"]}
  handlers:
    - include: handlers/main.yml
